### ISSUE TITLE
附属功能完善

### ISSUE THREAD

**Issue by Qian-F** [IllTamer/infinite-bot-3-expansion#5]
# 测试配置

服务端核心：purper-1.18.2-1632

客户端：fabric-1.18.2

服务端相关配置详见：https://github.com/Qian-F/QFserver-1.18.2

# ChatManager

## 服务器消息传回QQ群有换行

如下图：

![image.png](https://s2.loli.net/2023/01/31/5SXKWfkst7hHeLA.png)

## QQ群回复在游戏内显示效果不好

现在效果：

![image.png](https://s2.loli.net/2023/01/31/uS9yGkLpU63X8Jq.png)

#### 服务器内：

A：114514

#### Q群内：

机器人：A：114514

B：回复A：225625

#### 此时服务器内转发应为：

B：[回复 A] 225625

A应收到消息提醒：声音/文字

#### Q群内：

C：114514

D：回复C：225625

#### 此时服务器转发应为：

D：[回复C] 225625

## 支持更多的消息类型

1. 群公告
2. 名片类：网易云音乐分享等
3. 表情：现在转发信息为[表情]，期望为[doge]等QQ自带文字描述
4. 动画表情：转发消息与图片区分，目前全为[图片]

# DefenceManager

#### 配置文件：

​	isonlinemode：true/false

#### 命令：

/绑定 id

## 提供解绑命令

将basic中的绑定相关转移至此附属中并且提供解绑命令（服务器&qq群）

白名单和验证与绑定息息相关，而没有这些绑定就没有实质性作用

# GithubManager

提供对issue更新、Github action的监测

# MessageManager

- 提供帮助文档、暂时看不明白如何使用
- 对基础命令进行设置（eg：tps、list等）
- 实现Q群进行控制台命令输入功能（eg. #为触发前缀则Q群消息为：#tps、#list、#ban xxx）

**Comment by IllTamer** [comment]
> 下述文字中带有 `待解决`、`待更新` 的条目将在本体插件更新到 3.2.0(增加bc支持) 后进行更新

## ChatManager

- 换行为默认显示格式，属正常现象
- 重复 @ 问题待解决
- 群 -> 游戏 消息转发时，若目标qq绑定玩家账户且在线，配置项`parse-level`为1，则可收到提醒。如无法正常使用请检查上述情况。
- 更多消息类型支持待更新

## DefenceManager

- 绑定相关问题已采纳，待更新
- 绑定 / 解绑 操作为 BasicManager 固有，defence 提供的验证码绑定属增强作用，故此划分。

## GithubManager

- 提议采纳，待更新

## MessageManager

- 增加默认关键字配置的提议已采纳，待更新
- 触发方式可通过
	```yaml
	  # 触发器配置
	  trigger:
	    # 允许触发的消息来源
	    # - 'group': 仅群消息可触发
	    # - 'private': 仅私聊可触发
	    # - 'all': 不限制触发方式
	    source: 'group'
	    # 仅允许bot管理员触发
	    admin: true
	    # 是否仅允许已绑定玩家触发
	    bind: false
	    # 触发类型
	    # 'contains': 包含关键字触发
	    # 'equal': 完全匹配消息时触发
	    type: 'equal'
	    # 过滤器选项
	    # - true: 按触发器种类满足所有配置的关键字才可触发
	    # - false: 按触发器种类满足任意一配置的关键字即可触发
	    filter: true
	    # 关键字列表，为空时任意消息皆可触发
	    keys: ["#tps"]
	```
	进行个性化配置
